// examples/main-react/src/pages/Angular12.js
import React from "react";
import hostMap from "../hostMap";
import WujieReact from "wujie-react";
import { useNavigate } from "react-router-dom";

export default function Angular12() {
  const navigation = useNavigate();
  const angular12Url = hostMap("//localhost:7400/");
  const props = {
    jump: (name) => {
      navigation(`/${name}`);
    },
  };
  return (
    <WujieReact
      width="100%"
      height="100%"
      name="angular12"
      url={angular12Url}
      sync={true}
      props={props}
    ></WujieReact>
  );
}

// examples/main-angular/src/app/pages/angular12.component.ts
import { Component, OnInit } from "@angular/core";
import hostMap from "../../hostMap";

@Component({
  selector: "angular12",
  template: `<wujie-ngx
    width="100%"
    height="100%"
    [name]="'angular12'"
    [url]="angular12Url"
    [sync]="true"
    (change)="handleChange($event)"
  ></wujie-ngx>`,
})
export class Angular12Component implements OnInit {
  angular12Url = hostMap("//localhost:7400/");

  constructor() {}

  ngOnInit(): void {
    console.log("[angular12] init");
  }

  handleChange(e) {
    console.log("[angular12] change >", e);
  }
}
