// examples/main-vue/src/views/React16.vue
<template>
  <!--单例模式，name相同则复用一个无界实例，改变url则子应用重新渲染实例到对应路由 -->
  <WujieVue width="100%" height="100%" name="react16" :url="react16Url" :sync="true"></WujieVue>
</template>

<script>
import hostMap from "../hostMap";

export default {
  data() {
    return {
      react16Url: hostMap("//localhost:7600/") + (this.$route.params.path ? `${this.$route.params.path}` : ""),
    };
  },
};
</script>

<style lang="scss" scoped></style>

// examples/main-angular/src/app/pages/react16.component.ts
import { Component, OnInit } from "@angular/core";
import { ActivatedRoute } from "@angular/router";
import { filter } from "rxjs/operators";
import hostMap from "../../hostMap";

@Component({
  selector: "react16",
  template: `<wujie-ngx
    width="100%"
    height="100%"
    [name]="'react16'"
    [url]="react16Url"
    [sync]="true"
    (change)="handleChange($event)"
  ></wujie-ngx>`,
})
export class React16Component implements OnInit {
  react16Url = hostMap("//localhost:7600/");

  constructor(private activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    console.log("[react16] init");
    this.activatedRoute.params.pipe(filter(({ path }) => path)).subscribe(({ path }) => {
      this.react16Url = hostMap("//localhost:7600/") + path;
    });
  }

  handleChange(e) {
    console.log("[react16] change >", e);
  }
}
