// examples/main-react/src/pages/Angular12.js
import React from "react";
import hostMap from "../hostMap";
import WujieReact from "wujie-react";
import { useNavigate } from "react-router-dom";

export default function Angular12() {
  const navigation = useNavigate();
  const angular12Url = hostMap("//localhost:7400/");
  const props = {
    jump: (name) => {
      navigation(`/${name}`);
    },
  };
  return (
    <WujieReact
      width="100%"
      height="100%"
      name="angular12"
      url={angular12Url}
      sync={true}
      props={props}
    ></WujieReact>
  );
}

// examples/main-angular13/src/app/views/angular12.component.ts
import { Component} from '@angular/core';
import { hostMap } from '../../hostMap';

@Component({
  selector: 'app-angular12',
  template: `
    <!--单例模式，name相同则复用一个无界实例，改变url则子应用重新渲染实例到对应路由 -->
    <wujie-angular width="100%" height="100%" name="angular12" [url]="angular12Url" [sync]="true"></wujie-angular>
  `
})
export class Angular12Component {
  angular12Url = hostMap('//localhost:7400/');
}
