// examples/main-vue/src/views/React17.vue
<template>
  <!--保活模式，name相同则复用一个子应用实例，改变url无效，必须采用通信的方式告知路由变化 -->
  <WujieVue width="100%" height="100%" name="react17" :url="react17Url" :sync="true"></WujieVue>
</template>

<script>
import hostMap from "../hostMap";
export default {
  data() {
    return {
      react17Url: hostMap("//localhost:7100/"),
    };
  },
};
</script>

<style lang="scss" scoped></style>

// examples/main-angular13/src/app/views/react17.component.ts
import { Component } from '@angular/core';
import { hostMap } from '../../hostMap';

@Component({
  selector: 'app-react17',
  template: `
    <!--单例模式，name相同则复用一个无界实例，改变url则子应用重新渲染实例到对应路由 -->
    <wujie-angular width="100%" height="100%" name="react17" [url]="react17Url" [sync]="true"></wujie-angular>
  `
})
export class React17Component {
  react17Url = hostMap('//localhost:7100/');
}
