// examples/angular12/src/app/app.component.ts
import { Component, OnInit, NgZone } from '@angular/core';
import { ActivatedRoute, ActivationEnd, Router } from '@angular/router';
import { filter } from 'rxjs/operators';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.less']
})
export class AppComponent implements OnInit {
  constructor(private router: Router, private zone: NgZone) {
  }

  ngOnInit(): void {
    this.router.events.pipe(filter(event => event instanceof ActivationEnd)).subscribe(evt => {
      const url = (evt as ActivationEnd).snapshot.url.join('/');
      window.$wujie?.bus.$emit('sub-route-change', 'angular12', `/${url}`);
    });

    window.$wujie?.bus.$on('angular12-router-change', (path) => this.zone.run(() => this.router.navigate([path])));
  }
}



<div id="nav">
  <a [routerLink]="['/home']" routerLinkActive="router-link-exact-active">首页</a> |
  <a [routerLink]="['/dialog']" routerLinkActive="router-link-exact-active">弹窗</a> |
  <a [routerLink]="['/location']" routerLinkActive="router-link-exact-active">路由</a> |
  <a [routerLink]="['/contact']" routerLinkActive="router-link-exact-active">通信</a> |
  <a [routerLink]="['/state']" routerLinkActive="router-link-exact-active">状态</a>
</div>

<router-outlet></router-outlet>

// examples/vue3/src/App.vue
<template>
  <div id="nav" v-if="$route.name !== 'Postmessage'">
    <router-link to="/home">首页</router-link> | <router-link to="/dialog">弹窗</router-link> |
    <router-link to="/location">路由</router-link> | <router-link to="/contact">通信</router-link> |
    <router-link to="/state">状态</router-link> | <router-link to="/inline-event">内联事件</router-link>
  </div>
  <router-view />
</template>

<script>
export default {
  watch: {
    // 在 vue3-sub 路由下主动告知主应用路由跳转，主应用也跳到相应路由高亮菜单栏
    $route() {
      window.$wujie?.bus.$emit("sub-route-change", "vue3", this.$route.path);
    },
  },
  mounted() {
    window.$wujie?.bus.$on("vue3-router-change", (path) => this.$router.push(path));
  },
};
</script>
