// examples/main-angular13/src/app/home/home.component.ts
import {Component} from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.less']
})
export class HomeComponent {
  preload = window.localStorage.getItem('preload') !== 'false';
  degrade = window.localStorage.getItem('degrade') === 'true' || !window.Proxy || !window.CustomElementRegistry;
  disable = !window.Proxy || !window.CustomElementRegistry;

  onPreloadChange(val: boolean) {
    window.localStorage.setItem('preload', val.toString());
    setTimeout(() => window.location.reload(), 1000);
  }

  onDegradeChange(val: boolean) {
    window.localStorage.setItem('degrade', val.toString());
    setTimeout(() => window.location.reload(), 1000);
  }

  openLink(url: string) {
  }
}


<div class="home">
  <div class="tool">
    <button nz-button style="visibility: hidden" class="button-gap" nzType="primary" nzSize="large" >
      <i nz-icon nzType="unordered-list"></i>
    </button>
    <div class="button-list">
        <nz-switch
          class="switch button-gap"
          [nzDisabled]="disable"
          nzCheckedChildren="降级开"
          nzUnCheckedChildren="降级关"
          [(ngModel)]="degrade"
          (ngModelChange)="onDegradeChange($event)"
          nz-tooltip
          nzTooltipPlacement="bottom"
          nzTooltipTitle="主动降级，去除shadow+proxy"
        ></nz-switch>

        <nz-switch
          class="switch button-gap"
          nzCheckedChildren="预加载开"
          nzUnCheckedChildren="预加载关"
          [(ngModel)]="preload"
          (ngModelChange)="onPreloadChange($event)"
          nz-tooltip
          nzTooltipPlacement="bottom"
          nzTooltipTitle="预加载+预执行"
        ></nz-switch>


      <a href="https://wujie-micro.github.io/demo-main-react/" target="_blank" class="docs button-gap"
         rel="noreferrer"
         nz-tooltip
         nzTooltipPlacement="bottom"
         nzTooltipTitle="主应用为history模式"
         (click)="$event.stopPropagation();"
      >vue主应用</a>
      <a href="https://wujie-micro.github.io/demo-main-react/" target="_blank" class="docs button-gap"
         rel="noreferrer"
         nz-tooltip
         nzTooltipPlacement="bottom"
         nzTooltipTitle="主应用为hash模式"
         (click)="$event.stopPropagation();"
      >react主应用</a>

      <a href="https://github.com/Tencent/wujie" target="_blank" class="docs button-gap" (click)="$event.stopPropagation();">仓库</a>
      <a href="https://wujie-micro.github.io/doc/" target="_blank" class="docs button-gap" (click)="$event.stopPropagation();">文档</a>
    </div>
  </div>
  <h1 class="header">
    <img
      [ngStyle]="{ width: '70px', height: '70px', 'margin-right': '15px' }"
      src="https://vfiles.gtimg.cn/wuji_dashboard/xy/test_wuji_damy/XC5WMbxE.svg"
    />
    <span class="bland">无界</span>
  </h1>

  <h2 class="subtitle">—极致的微前端框架</h2>

  <div class="detail-content">
    <div class="item">
      <div class="title">极速 🚀</div>
      <div class="detail">
        <ul>
          <li>极致预加载提速</li>
          <li>应用秒开无白屏</li>
          <li>应用丝滑般切换</li>
        </ul>
      </div>
    </div>
    <div class="item">
      <div class="title">强大 💪</div>
      <div class="detail">
        <ul>
          <li>多应用同时激活在线</li>
          <li>应用级别保活</li>
          <li>去中心化的通信</li>
        </ul>
      </div>
    </div>
    <div class="item">
      <div class="title">简单 🤞</div>
      <div class="detail">
        <ul>
          <li>更小的体积</li>
          <li>精简的API</li>
          <li>开箱即用</li>
        </ul>
      </div>
    </div>
  </div>
</div>

// examples/main-react/src/pages/Home.js
import React from "react";
import Switch from "antd/es/switch";
import Tooltip from "antd/es/tooltip";
import Button from "antd/es/button";
import { UnorderedListOutlined } from "@ant-design/icons";

export default class Home extends React.Component {
  state = {
    checkState: window.localStorage.getItem("preload") !== "false",
    disable: !window.Proxy || !window.CustomElementRegistry,
    degradeState: window.localStorage.getItem("degrade") === "true" || !window.Proxy || !window.CustomElementRegistry,
  };
  checkStateChange = (check) => {
    window.localStorage.setItem("preload", check);
    setTimeout(() => window.location.reload(), 1000);
  };
  degradeStateChange = (check) => {
    window.localStorage.setItem("degrade", check);
    setTimeout(() => window.location.reload(), 1000);
  };
  handleClick = (e) => {
    this.props.changeActive(true);
    e.stopPropagation();
  };

  render() {
    return (
      <div className="home">
        <div className="tool">
          <Button
            type="primary"
            style={{ visibility: "hidden" }}
            icon={<UnorderedListOutlined />}
          ></Button>
          <div className="button-list">
            <Tooltip title="主动降级，去除shadow+proxy">
              <Switch
                className="switch button-gap"
                checkedChildren="降级开"
                unCheckedChildren="降级关"
                disabled={this.state.disable}
                defaultChecked={this.state.degradeState}
                onChange={this.degradeStateChange}
              ></Switch>
            </Tooltip>
            <Tooltip title="预加载+预执行">
              <Switch
                className="switch button-gap"
                checkedChildren="预加载开"
                unCheckedChildren="预加载关"
                defaultChecked={this.state.checkState}
                onChange={this.checkStateChange}
              ></Switch>
            </Tooltip>
            <Tooltip title="主应用为history模式">
              <a
                href="https://wujie-micro.github.io/demo-main-vue/"
                target="_blank"
                className="docs button-gap"
                rel="noreferrer"
              >
                vue主应用
              </a>
            </Tooltip>
            <Tooltip title="主应用为hash模式">
              <a
                  href="https://wujie-micro.github.io/demo-main-angular/"
                  target="_blank"
                  className="docs button-gap"
                  rel="noreferrer"
              >
                angular主应用
              </a>
            </Tooltip>
            <a href="https://github.com/Tencent/wujie" target="_blank" className="docs button-gap" rel="noreferrer">
              仓库
            </a>
            <a href="https://wujie-micro.github.io/doc/" target="_blank" className="docs button-gap" rel="noreferrer">
              文档
            </a>
          </div>
        </div>
        <h1 className="header">
          <img
            alt="图片"
            style={{ width: "70px", height: "70px", marginRight: "15px" }}
            src="https://vfiles.gtimg.cn/wuji_dashboard/xy/test_wuji_damy/XC5WMbxE.svg"
          />
          <span className="bland">无界</span>
        </h1>
        <h2 className="subtitle">—极致的微前端框架</h2>

        <div className="detail-content">
          <div className="item">
            <div className="title">极速 🚀</div>
            <div className="detail">
              <ul>
                <li>极致预加载提速</li>
                <li>应用秒开无白屏</li>
                <li>应用丝滑般切换</li>
              </ul>
            </div>
          </div>
          <div className="item">
            <div className="title">强大 💪</div>
            <div className="detail">
              <ul>
                <li>多应用同时激活在线</li>
                <li>应用级别保活</li>
                <li>去中心化的通信</li>
              </ul>
            </div>
          </div>
          <div className="item">
            <div className="title">简单 🤞</div>
            <div className="detail">
              <ul>
                <li>更小的体积</li>
                <li>精简的API</li>
                <li>开箱即用</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    );
  }
}
