// examples/main-angular13/src/app/views/react17-sub.component.ts
import { Component } from '@angular/core';
import { hostMap } from '../../hostMap';
import { ActivatedRoute } from '@angular/router';
import { WujieComponent } from 'wujie-angular';

@Component({
  selector: 'app-react17-sub',
  template: `
    <!--单例模式，name相同则复用一个无界实例，改变url则子应用重新渲染实例到对应路由 -->
    <wujie-angular width="100%" height="100%" name="react17" [url]="react17Url"></wujie-angular>
  `
})
export class React17SubComponent {

  private readonly url = hostMap('//localhost:7100/');
  react17Url = this.url;

  constructor(private route: ActivatedRoute) {
    route.params.subscribe(params => {
      this.react17Url = this.url + params['path'];
      WujieComponent.bus.$emit('react17-router-change', params['path']);
    });
  }
}

// examples/main-vue/src/views/React17-sub.vue
<template>
  <!--保活模式，name相同则复用一个子应用实例，改变url无效，必须采用通信的方式告知路由变化 -->
  <WujieVue width="100%" height="100%" name="react17" :url="react17Url"></WujieVue>
</template>

<script>
import hostMap from '../hostMap'
import wujieVue from 'wujie-vue2'
export default {
  data() {
    return {
      react17Url: hostMap('//localhost:7100/') + this.$route.params.path
    }
  },
  watch: {
    $route() {
      wujieVue.bus.$emit('react17-router-change', `/${this.$route.params.path}`)
    }
  }
}
</script>

<style lang="scss" scoped></style>
