// examples/main-angular13/src/app/views/react16.component.ts
import { Component } from '@angular/core';
import { hostMap } from '../../hostMap';

@Component({
  selector: 'app-react16',
  template: `
    <!--单例模式，name相同则复用一个无界实例，改变url则子应用重新渲染实例到对应路由 -->

    <wujie-angular width="100%" height="100%" name="react16" [url]="react16Url" [sync]="true"></wujie-angular>
  `
})
export class React16Component {
  react16Url = hostMap('//localhost:7600/');
}

// examples/main-vue/src/views/React16.vue
<template>
  <!--单例模式，name相同则复用一个无界实例，改变url则子应用重新渲染实例到对应路由 -->
  <WujieVue width="100%" height="100%" name="react16" :url="react16Url" :sync="true"></WujieVue>
</template>

<script>
import hostMap from "../hostMap";

export default {
  data() {
    return {
      react16Url: hostMap("//localhost:7600/"),
    };
  },
};
</script>

<style lang="scss" scoped></style>
