// examples/vue3/src/views/Home.vue
<template>
  <div>
    <HelloWorld msg="Vue3示例"></HelloWorld>
    <div class="content" style="text-align: center">
      <p>
        当前vue版本
        <el-tag style="vertical-align: text-top" size="small">3.2.24</el-tag>
      </p>
      <p>
        当前element版本
        <el-tag style="vertical-align: text-top" size="small">2.2.6</el-tag>
      </p>
      <p>
        当前ant-design-vue版本
        <el-tag style="vertical-align: text-top" size="small">2.2.8</el-tag>
      </p>
      <p>
        <el-button @click="() => open('https://github.com/Tencent/wujie/tree/master/examples/vue3')"
          >仓库地址</el-button
        >
      </p>
    </div>
  </div>
</template>

<script>
import HelloWorld from "@/components/HelloWorld.vue";
export default {
  data() {
    return {
      open: window.open
    };
  },
  components: {
    HelloWorld
  }
};
</script>

<style>
:root {
  --host-color: #f16b5f;
}
</style>

// examples/angular12/src/app/views/home/home.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.less']
})
export class HomeComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}


<app-hello-world>Angular 12 示例</app-hello-world>
<div class="content" style="text-align: center">
  <p>
    当前angular版本
    <nz-tag style="vertical-align: text-top" nzColor="processing">12.2.16</nz-tag>
  </p>
  <p>
    当前ng-zorro-antd版本
    <nz-tag style="vertical-align: text-top" nzColor="processing">12.1.1</nz-tag>
  </p>
  <p>
    <a nz-button href="https://github.com/Tencent/wujie/tree/master/examples/angular12" (click)="$event.stopPropagation()" target="_blank">仓库地址</a >
  </p>
</div>
