// examples/main-angular13/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, ActivationEnd, Router } from '@angular/router';
import { filter } from 'rxjs';
import { pathChangeObservable } from '../path-change';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.less']
})
export class AppComponent implements OnInit {
  active = false;
  react16Flag = false;
  react17Flag = false;
  vue2Flag = false;
  vue3Flag = false;
  viteFlag = false;

  constructor(private activatedRoute: ActivatedRoute, private router: Router) {}

  ngOnInit(): void {
    this.router.events.pipe(filter(event => event instanceof ActivationEnd)).subscribe(evt => {
      const routeName = (evt as ActivationEnd).snapshot.data['name'];
      this.react16Flag = routeName === 'react16-sub';
      this.react17Flag = routeName === 'react17-sub';
      this.vue2Flag = routeName === 'vue2-sub';
      this.vue3Flag = routeName === 'vue3-sub';
      this.viteFlag = routeName === 'vite-sub';
    });

    pathChangeObservable.subscribe(path => this.router.navigate([path]));
  }

  close() {
    this.active = false;
  }

  handleFlag(evt: MouseEvent, name: keyof AppComponent) {
    evt.preventDefault();
    evt.stopPropagation();
    // @ts-ignore
    this[name] = !this[name];
  }
}

<div id="nav" [class.active]="active" (click)="close()">
  <div class="nav-inner">
    <a routerLinkActive="router-link-active" [routerLink]="['/home']" >介绍</a>
    <!-- react16相关路由 -->
    <a routerLinkActive="router-link-active" [routerLink]="['/react16']">
      react16
      <i nz-icon class="main-icon"  [class.active]="react16Flag" nzType="caret-up" (click)="handleFlag($event, 'react16Flag')" ></i>
    </a>
    <div class="sub-menu" [hidden]="!react16Flag">
      <a routerLinkActive="router-link-active" [routerLink]="['/react16-sub/home']">home</a>
      <a routerLinkActive="router-link-active" [routerLink]="['/react16-sub/dialog']">dialog</a>
      <a routerLinkActive="router-link-active" [routerLink]="['/react16-sub/location']">location</a>
      <a routerLinkActive="router-link-active" [routerLink]="['/react16-sub/communication']">communication</a>
      <a routerLinkActive="router-link-active" [routerLink]="['/react16-sub/nest']">nest</a>
      <a routerLinkActive="router-link-active" [routerLink]="['/react16-sub/font']">font</a>
    </div>
    <!-- react17相关路由 -->
    <a routerLinkActive="router-link-active" [routerLink]="['/react17']">
      react17
      <span class="alive">保活</span>
      <i nz-icon class="main-icon" [class.active]="react17Flag" nzType="caret-up"  (click)="handleFlag($event, 'react17Flag')"></i>
    </a>
    <div class="sub-menu" [hidden]="!react17Flag">
      <a routerLinkActive="router-link-active" [routerLink]="['/react17-sub/home']">home</a>
      <a routerLinkActive="router-link-active" [routerLink]="['/react17-sub/dialog']">dialog</a>
      <a routerLinkActive="router-link-active" [routerLink]="['/react17-sub/location']">location</a>
      <a routerLinkActive="router-link-active" [routerLink]="['/react17-sub/communication']">communication</a>
      <a routerLinkActive="router-link-active" [routerLink]="['/react17-sub/state']">state</a>
    </div>
    <!-- vue2相关路由 -->
    <a routerLinkActive="router-link-active" [routerLink]="['/vue2']">
      vue2
      <i nz-icon class="main-icon" [class.active]="vue2Flag" nzType="caret-up" (click)="handleFlag($event, 'vue2Flag')"></i>
    </a>
    <div class="sub-menu" [hidden]="!vue2Flag">
      <a routerLinkActive="router-link-active" [routerLink]="['/vue2-sub/home']">home</a>
      <a routerLinkActive="router-link-active" [routerLink]="['/vue2-sub/dialog']">dialog</a>
      <a routerLinkActive="router-link-active" [routerLink]="['/vue2-sub/location']">location</a>
      <a routerLinkActive="router-link-active" [routerLink]="['/vue2-sub/communication']">communication</a>
    </div>
    <!-- vue3相关路由 -->
    <a routerLinkActive="router-link-active" [routerLink]="['/vue3']">
      vue3<span class="alive">保活</span>
      <i nz-icon class="main-icon" [class.active]="vue3Flag" nzType="caret-up"  (click)="handleFlag($event, 'vue3Flag')"></i>
    </a>
    <div class="sub-menu" [hidden]="!vue3Flag">
      <a routerLinkActive="router-link-active" [routerLink]="['/vue3-sub/home']">home</a>
      <a routerLinkActive="router-link-active" [routerLink]="['/vue3-sub/dialog']">dialog</a>
      <a routerLinkActive="router-link-active" [routerLink]="['/vue3-sub/location']">location</a>
      <a routerLinkActive="router-link-active" [routerLink]="['/vue3-sub/contact']">contact</a>
      <a routerLinkActive="router-link-active" [routerLink]="['/vue3-sub/state']">state</a>
    </div>
    <a routerLinkActive="router-link-active" [routerLink]="['/vite']"
    >vite
      <i nz-icon class="main-icon" nzType="caret-up" [class.active]="viteFlag" (click)="handleFlag($event, 'viteFlag')"></i>
    </a>
    <div class="sub-menu" [hidden]="!viteFlag">
      <a routerLinkActive="router-link-active" [routerLink]="['/vite-sub/home']">home</a>
      <a routerLinkActive="router-link-active" [routerLink]="['/vite-sub/dialog']">dialog</a>
      <a routerLinkActive="router-link-active" [routerLink]="['/vite-sub/location']">location</a>
      <a routerLinkActive="router-link-active" [routerLink]="['/vite-sub/contact']">contact</a>
    </div>
    <a routerLinkActive="router-link-active" [routerLink]="['/angular12']">angular12</a>
    <a routerLinkActive="router-link-active" [routerLink]="['/all']">all</a>
  </div>
  <button nz-button class="menu-icon" nzType="primary" nzSize="large" (click)="$event.stopPropagation(); active = !active" >
    <i nz-icon nzType="unordered-list"></i>
  </button>
</div>
<div class="content" (click)="$event.stopPropagation();$event.preventDefault(); active = false">
  <router-outlet></router-outlet>
</div>

// examples/main-react/src/App.js
import { HashRouter as Router, Route, Routes, NavLink, Navigate, useLocation, useNavigate } from "react-router-dom";
import WujieReact from "wujie-react";
import React, { useState } from "react";
import Home from "./pages/Home";
import React16 from "./pages/React16";
import React17 from "./pages/React17";
import Vue2 from "./pages/Vue2";
import Vue3 from "./pages/Vue3";
import Vite from "./pages/Vite";
import Angular12 from "./pages/Angular12";
import All from "./pages/All";
import Button from "antd/es/button";
import { UnorderedListOutlined, CaretUpOutlined } from "@ant-design/icons";

const { bus } = WujieReact;

const subMap = {
  react16: ["home", "dialog", "location", "communication", "nest", "font"],
  react17: ["home", "dialog", "location", "communication", "state"],
  vue2: ["home", "dialog", "location", "communication"],
  vue3: ["home", "dialog", "location", "contact", "state"],
  vite: ["home", "dialog", "location", "contact"],
};

function Nav() {
  const location = useLocation();
  const navigation = useNavigate(); 
  const [react16Flag, setReact16Flag] = useState(location.pathname.includes("react16-sub"));
  const [react17Flag, setReact17Flag] = useState(location.pathname.includes("react7-sub"));
  const [vue2Flag, setVue2Flag] = useState(location.pathname.includes("vue2-sub"));
  const [vue3Flag, setVue3Flag] = useState(location.pathname.includes("vue3-sub"));
  const [viteFlag, setViteFlag] = useState(location.pathname.includes("vite-sub"));
  const degrade = window.Proxy


  const handleFlag = (name) => {
    switch (name) {
      case "react16":
        setReact16Flag(!react16Flag);
        break;
      case "react17":
        setReact17Flag(!react17Flag);
        break;
      case "vue2":
        setVue2Flag(!vue2Flag);
        break;
      case "vue3":
        setVue3Flag(!vue3Flag);
        break;
      case "vite":
        setViteFlag(!viteFlag);
        break;
      default:
        break;
    }
  };
  return (
    <nav>
      <NavLink to="/home" className={({ isActive }) => (isActive ? "active" : "inactive")}>
        介绍
      </NavLink>
      <NavLink to="/react16" className={({ isActive }) => (isActive ? "active" : "inactive")}>
        react16
        <CaretUpOutlined
          className={react16Flag ? "main-icon active" : "main-icon"}
          onClick={() => handleFlag("react16")}
        />
      </NavLink>
      <div className="sub-menu" style={{display: react16Flag ? "block" : "none"}}>
        {subMap.react16.map((item) => (
          <NavLink to={`/react16-sub/${item}`} key={item} className={({ isActive }) => (isActive ? "active" : "inactive")}>
            {item}
          </NavLink>
        ))}
      </div>
      <NavLink to="/react17" className={({ isActive }) => (isActive ? "active" : "inactive")}>
        react17<span className="alive">保活</span>
        <CaretUpOutlined
          className={react17Flag ? "main-icon active" : "main-icon"}
          onClick={() => handleFlag("react17")}
        />
      </NavLink>
      <div className="sub-menu" style={{display: react17Flag ? "block" : "none"}}>
        {subMap.react17.map((item) => (
          <NavLink to={`/react17-sub/${item}`} key={item} className={({ isActive }) => (isActive ? "active" : "inactive")}>
            {item}
          </NavLink>
        ))}
      </div>
      <NavLink to="/vue2" className={({ isActive }) => (isActive ? "active" : "inactive")}>
        vue2
        <CaretUpOutlined className={vue2Flag ? "main-icon active" : "main-icon"} onClick={() => handleFlag("vue2")} />
      </NavLink>
      <div className="sub-menu" style={{display: vue2Flag ? "block" : "none"}}>
        {subMap.vue2.map((item) => (
          <NavLink to={`/vue2-sub/${item}`} key={item} className={({ isActive }) => (isActive ? "active" : "inactive")}>
            {item}
          </NavLink>
        ))}
      </div>
      {degrade && <NavLink to="/vue3" className={({ isActive }) => (isActive ? "active" : "inactive")}>
        vue3<span className="alive">保活</span>
        <CaretUpOutlined className={vue3Flag ? "main-icon active" : "main-icon"} onClick={() => handleFlag("vue3")} />
      </NavLink>}
      <div className="sub-menu" style={{display: vue3Flag ? "block" : "none"}}>
        {subMap.vue3.map((item) => (
          <NavLink to={`/vue3-sub/${item}`} key={item} className={({ isActive }) => (isActive ? "active" : "inactive")}>
            {item}
          </NavLink>
        ))}
      </div>
       {degrade && <NavLink to="/vite" className={({ isActive }) => (isActive ? "active" : "inactive")}>
        vite
        <CaretUpOutlined className={viteFlag ? "main-icon active" : "main-icon"} onClick={() => handleFlag("vite")} />
      </NavLink>}
      <div className="sub-menu" style={{display: viteFlag ? "block" : "none"}}>
        {subMap.vite.map((item) => (
          <NavLink to={`/vite-sub/${item}`} key={item} className={({ isActive }) => (isActive ? "active" : "inactive")}>
            {item}
          </NavLink>
        ))}
      </div>
      <NavLink to="/angular12" className={({ isActive }) => (isActive ? "active" : "inactive")}>
        angular12
      </NavLink>
      <NavLink to="/all" className={({ isActive }) => (isActive ? "active" : "inactive")}>
        all
      </NavLink>
      <Button type="primary" className="menu-icon" icon={<UnorderedListOutlined />}></Button>
    </nav>
  );
}

class App extends React.PureComponent {
  state = {
    active: false,
  };
  changeActive = (val) => {
    this.setState({ active: val });
  };
  render() {
    return (
      <div className="app">
        <Router>
          <div className={this.state.active ? "nav active" : "nav"}>
            <Nav />
          </div>
          <div className="content" onClick={() => this.changeActive(false)}>
            <Routes>
              <Route exact path="/home" element={<Home changeActive={this.changeActive} />} />
              <Route exact path="/react16" element={<React16 />} />
              <Route exact path="/react16-sub/:path" element={<React16 />} />
              <Route exact path="/react17" element={<React17 />} />
              <Route exact path="/react17-sub/:path" element={<React17 />} />
              <Route exact path="/vue2" element={<Vue2 />} />
              <Route exact path="/vue2-sub/:path" element={<Vue2 />} />
              <Route exact path="/vue3" element={<Vue3 />} />
              <Route exact path="/vue3-sub/:path" element={<Vue3 />} />
              <Route exact path="/vite" element={<Vite />} />
              <Route exact path="/vite-sub/:path" element={<Vite />} />
              <Route exact path="/angular12" element={<Angular12 />} />
              <Route exact path="/all" element={<All />} />
              <Route path="*" element={<Navigate to="/home" replace />} />
            </Routes>
          </div>
        </Router>
      </div>
    );
  }
}

export default App;
