// examples/main-angular/src/app/app.component.ts
import { Component, VERSION } from "@angular/core";

@Component({
  selector: "my-app",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
})
export class AppComponent {
  name = "Angular " + VERSION.major;

  active = false;
  react16Flag = false;
  react17Flag = false;
  vue2Flag = false;
  vue3Flag = false;
  viteFlag = false;

  constructor() {}

  close() {
    if (this.active) this.active = false;
  }

  handleFlag(name) {
    this[name + "Flag"] = !this[name + "Flag"];
  }
}

<div id="app">
  <div id="nav" [class.active]="active" (click)="close()">
    <a [routerLink]="['/home']" routerLinkActive="router-link-active">介绍 </a>
    <!-- react16相关路由 -->
    <a [routerLink]="['/react16']" routerLinkActive="router-link-active">
      react16
      <span
        nz-icon
        nzType="caret-up"
        class="main-icon"
        [ngClass]="{ active: react16Flag }"
        nzTheme="outline"
        (click)="handleFlag('react16')"
      ></span>
    </a>
    <div class="sub-menu" [hidden]="!react16Flag">
      <a [routerLink]="['/react16-sub/home']" routerLinkActive="router-link-active">home</a>
      <a [routerLink]="['/react16-sub/dialog']" routerLinkActive="router-link-active">dialog</a>
      <a [routerLink]="['/react16-sub/location']" routerLinkActive="router-link-active">location</a>
      <a [routerLink]="['/react16-sub/communication']" routerLinkActive="router-link-active">communication</a>
      <a [routerLink]="['/react16-sub/nest']" routerLinkActive="router-link-active">nest</a>
      <a [routerLink]="['/react16-sub/font']" routerLinkActive="router-link-active">font</a>
    </div>

    <!-- react17相关路由 -->
    <a [routerLink]="['/react17']" routerLinkActive="router-link-active">
      react17
      <span class="alive">保活</span>
      <span
        nz-icon
        nzType="caret-up"
        class="main-icon"
        [ngClass]="{ active: react17Flag }"
        nzTheme="outline"
        (click)="handleFlag('react17')"
      ></span>
    </a>
    <div class="sub-menu" [hidden]="!react17Flag">
      <a [routerLink]="['/react17-sub/home']" routerLinkActive="router-link-active">home</a>
      <a [routerLink]="['/react17-sub/dialog']" routerLinkActive="router-link-active">dialog</a>
      <a [routerLink]="['/react17-sub/location']" routerLinkActive="router-link-active">location</a>
      <a [routerLink]="['/react17-sub/communication']" routerLinkActive="router-link-active">communication</a>
      <a [routerLink]="['/react17-sub/state']" routerLinkActive="router-link-active">state</a>
    </div>

    <!-- vue2相关路由 -->
    <a [routerLink]="['/vue2']" routerLinkActive="router-link-active">
      vue2
      <span
        nz-icon
        nzType="caret-up"
        class="main-icon"
        [ngClass]="{ active: vue2Flag }"
        nzTheme="outline"
        (click)="handleFlag('vue2')"
      ></span>
    </a>
    <div class="sub-menu" [hidden]="!vue2Flag">
      <a [routerLink]="['/vue2-sub/home']" routerLinkActive="router-link-active">home</a>
      <a [routerLink]="['/vue2-sub/dialog']" routerLinkActive="router-link-active">dialog</a>
      <a [routerLink]="['/vue2-sub/location']" routerLinkActive="router-link-active">location</a>
      <a [routerLink]="['/vue2-sub/communication']" routerLinkActive="router-link-active">communication</a>
    </div>

    <!-- vue3相关路由 -->
    <a [routerLink]="['/vue3']" routerLinkActive="router-link-active">
      vue3
      <span class="alive">保活</span>
      <span
        nz-icon
        nzType="caret-up"
        class="main-icon"
        [ngClass]="{ active: vue3Flag }"
        nzTheme="outline"
        (click)="handleFlag('vue3')"
      ></span>
    </a>
    <div class="sub-menu" [hidden]="!vue3Flag">
      <a [routerLink]="['/vue3-sub/home']" routerLinkActive="router-link-active">home</a>
      <a [routerLink]="['/vue3-sub/dialog']" routerLinkActive="router-link-active">dialog</a>
      <a [routerLink]="['/vue3-sub/location']" routerLinkActive="router-link-active">location</a>
      <a [routerLink]="['/vue3-sub/contact']" routerLinkActive="router-link-active">contact</a>
      <a [routerLink]="['/vue3-sub/state']" routerLinkActive="router-link-active">state</a>
    </div>

    <!-- vite相关路由 -->
    <a [routerLink]="['/vite']" routerLinkActive="router-link-active">
      vite
      <span
        nz-icon
        nzType="caret-up"
        class="main-icon"
        [ngClass]="{ active: viteFlag }"
        nzTheme="outline"
        (click)="handleFlag('vite')"
      ></span>
    </a>
    <div class="sub-menu" [hidden]="!viteFlag">
      <a [routerLink]="['/vite-sub/home']" routerLinkActive="router-link-active">home</a>
      <a [routerLink]="['/vite-sub/dialog']" routerLinkActive="router-link-active">dialog</a>
      <a [routerLink]="['/vite-sub/location']" routerLinkActive="router-link-active">location</a>
      <a [routerLink]="['/vite-sub/contact']" routerLinkActive="router-link-active">contact</a>
    </div>

    <a [routerLink]="['/angular12']" routerLinkActive="router-link-active">angular12</a>
    <a [routerLink]="['/all']" routerLinkActive="router-link-active">all</a>
  </div>
  <div class="content" (click)="active = false">
    <router-outlet></router-outlet>
  </div>
</div>

// examples/main-react/src/App.js
import { HashRouter as Router, Route, Routes, NavLink, Navigate, useLocation, useNavigate } from "react-router-dom";
import WujieReact from "wujie-react";
import React, { useState } from "react";
import Home from "./pages/Home";
import React16 from "./pages/React16";
import React17 from "./pages/React17";
import Vue2 from "./pages/Vue2";
import Vue3 from "./pages/Vue3";
import Vite from "./pages/Vite";
import Angular12 from "./pages/Angular12";
import All from "./pages/All";
import Button from "antd/es/button";
import { UnorderedListOutlined, CaretUpOutlined } from "@ant-design/icons";

const { bus } = WujieReact;

const subMap = {
  react16: ["home", "dialog", "location", "communication", "nest", "font"],
  react17: ["home", "dialog", "location", "communication", "state"],
  vue2: ["home", "dialog", "location", "communication"],
  vue3: ["home", "dialog", "location", "contact", "state"],
  vite: ["home", "dialog", "location", "contact"],
};

function Nav() {
  const location = useLocation();
  const navigation = useNavigate(); 
  const [react16Flag, setReact16Flag] = useState(location.pathname.includes("react16-sub"));
  const [react17Flag, setReact17Flag] = useState(location.pathname.includes("react7-sub"));
  const [vue2Flag, setVue2Flag] = useState(location.pathname.includes("vue2-sub"));
  const [vue3Flag, setVue3Flag] = useState(location.pathname.includes("vue3-sub"));
  const [viteFlag, setViteFlag] = useState(location.pathname.includes("vite-sub"));
  const degrade = window.Proxy


  const handleFlag = (name) => {
    switch (name) {
      case "react16":
        setReact16Flag(!react16Flag);
        break;
      case "react17":
        setReact17Flag(!react17Flag);
        break;
      case "vue2":
        setVue2Flag(!vue2Flag);
        break;
      case "vue3":
        setVue3Flag(!vue3Flag);
        break;
      case "vite":
        setViteFlag(!viteFlag);
        break;
      default:
        break;
    }
  };
  return (
    <nav>
      <NavLink to="/home" className={({ isActive }) => (isActive ? "active" : "inactive")}>
        介绍
      </NavLink>
      <NavLink to="/react16" className={({ isActive }) => (isActive ? "active" : "inactive")}>
        react16
        <CaretUpOutlined
          className={react16Flag ? "main-icon active" : "main-icon"}
          onClick={() => handleFlag("react16")}
        />
      </NavLink>
      <div className="sub-menu" style={{display: react16Flag ? "block" : "none"}}>
        {subMap.react16.map((item) => (
          <NavLink to={`/react16-sub/${item}`} key={item} className={({ isActive }) => (isActive ? "active" : "inactive")}>
            {item}
          </NavLink>
        ))}
      </div>
      <NavLink to="/react17" className={({ isActive }) => (isActive ? "active" : "inactive")}>
        react17<span className="alive">保活</span>
        <CaretUpOutlined
          className={react17Flag ? "main-icon active" : "main-icon"}
          onClick={() => handleFlag("react17")}
        />
      </NavLink>
      <div className="sub-menu" style={{display: react17Flag ? "block" : "none"}}>
        {subMap.react17.map((item) => (
          <NavLink to={`/react17-sub/${item}`} key={item} className={({ isActive }) => (isActive ? "active" : "inactive")}>
            {item}
          </NavLink>
        ))}
      </div>
      <NavLink to="/vue2" className={({ isActive }) => (isActive ? "active" : "inactive")}>
        vue2
        <CaretUpOutlined className={vue2Flag ? "main-icon active" : "main-icon"} onClick={() => handleFlag("vue2")} />
      </NavLink>
      <div className="sub-menu" style={{display: vue2Flag ? "block" : "none"}}>
        {subMap.vue2.map((item) => (
          <NavLink to={`/vue2-sub/${item}`} key={item} className={({ isActive }) => (isActive ? "active" : "inactive")}>
            {item}
          </NavLink>
        ))}
      </div>
      {degrade && <NavLink to="/vue3" className={({ isActive }) => (isActive ? "active" : "inactive")}>
        vue3<span className="alive">保活</span>
        <CaretUpOutlined className={vue3Flag ? "main-icon active" : "main-icon"} onClick={() => handleFlag("vue3")} />
      </NavLink>}
      <div className="sub-menu" style={{display: vue3Flag ? "block" : "none"}}>
        {subMap.vue3.map((item) => (
          <NavLink to={`/vue3-sub/${item}`} key={item} className={({ isActive }) => (isActive ? "active" : "inactive")}>
            {item}
          </NavLink>
        ))}
      </div>
       {degrade && <NavLink to="/vite" className={({ isActive }) => (isActive ? "active" : "inactive")}>
        vite
        <CaretUpOutlined className={viteFlag ? "main-icon active" : "main-icon"} onClick={() => handleFlag("vite")} />
      </NavLink>}
      <div className="sub-menu" style={{display: viteFlag ? "block" : "none"}}>
        {subMap.vite.map((item) => (
          <NavLink to={`/vite-sub/${item}`} key={item} className={({ isActive }) => (isActive ? "active" : "inactive")}>
            {item}
          </NavLink>
        ))}
      </div>
      <NavLink to="/angular12" className={({ isActive }) => (isActive ? "active" : "inactive")}>
        angular12
      </NavLink>
      <NavLink to="/all" className={({ isActive }) => (isActive ? "active" : "inactive")}>
        all
      </NavLink>
      <Button type="primary" className="menu-icon" icon={<UnorderedListOutlined />}></Button>
    </nav>
  );
}

class App extends React.PureComponent {
  state = {
    active: false,
  };
  changeActive = (val) => {
    this.setState({ active: val });
  };
  render() {
    return (
      <div className="app">
        <Router>
          <div className={this.state.active ? "nav active" : "nav"}>
            <Nav />
          </div>
          <div className="content" onClick={() => this.changeActive(false)}>
            <Routes>
              <Route exact path="/home" element={<Home changeActive={this.changeActive} />} />
              <Route exact path="/react16" element={<React16 />} />
              <Route exact path="/react16-sub/:path" element={<React16 />} />
              <Route exact path="/react17" element={<React17 />} />
              <Route exact path="/react17-sub/:path" element={<React17 />} />
              <Route exact path="/vue2" element={<Vue2 />} />
              <Route exact path="/vue2-sub/:path" element={<Vue2 />} />
              <Route exact path="/vue3" element={<Vue3 />} />
              <Route exact path="/vue3-sub/:path" element={<Vue3 />} />
              <Route exact path="/vite" element={<Vite />} />
              <Route exact path="/vite-sub/:path" element={<Vite />} />
              <Route exact path="/angular12" element={<Angular12 />} />
              <Route exact path="/all" element={<All />} />
              <Route path="*" element={<Navigate to="/home" replace />} />
            </Routes>
          </div>
        </Router>
      </div>
    );
  }
}

export default App;
